# Configure.
language: python
python:
  - 3.6
  - 3.4
  - pypy
  - 3.8
services:
  - redis-server
  - rabbitmq
  - mysql
  - postgresql
sudo: false

# Environment and matrix.
env:
  - BROKER=sqlite RESULT=sqlite LOCK=sqlite
  - BROKER=mysql RESULT=mysql LOCK=mysql
  - BROKER=rabbit RESULT=redis LOCK=redis
  - BROKER=rabbit RESULT=redis LOCK=filesystem
  - BROKER=postgres RESULT=postgres LOCK=postgres
  - BROKER=redis RESULT=redis LOCK=redis
  - BROKER=redis_sock RESULT=redis_sock LOCK=redis_sock
matrix:
  include:
    - python: 3.6
      services: []
      env: TOX_ENV=lint
      before_script: []
      after_success: []

# Run.
install: pip install tox
before_script:
  - ./testdata/travis/setup.sh

script: tox -e ${TOX_ENV:-py}
after_success:
  - bash <(curl -s https://codecov.io/bash)

