# Configure.
services:
  - mysql
  - postgresql

cache:
  - "%HOMEDRIVE%%HOMEPATH%\rabbitmq-server-3.7.6.exe"

# Environment and matrix.
environment:
  PATH: C:\%PYTHON%;C:\%PYTHON%\Scripts;C:\Program Files\MySQL\MySQL Server 5.7\bin;C:\Program Files\PostgreSQL\9.5\bin;%PATH%
  PGPASSWORD: Password12!
  PYTHON: Python36
  matrix:
    - TOX_ENV: lint
      BROKER: rabbit
      RESULT: redis
      LOCK: redis
    - TOX_ENV: py37
      BROKER: rabbit
      RESULT: redis
      LOCK: redis
    - TOX_ENV: py36
      BROKER: rabbit
      RESULT: redis
      LOCK: redis
    - TOX_ENV: py
      PYTHON: Python37-x64
      BROKER: rabbit
      RESULT: redis
      LOCK: redis
    - TOX_ENV: py
      PYTHON: Python36-x64
      BROKER: rabbit
      RESULT: redis
      LOCK: redis

    - TOX_ENV: lint
      BROKER: rabbit
      RESULT: redis
      LOCK: filesystem
    - TOX_ENV: py37
      BROKER: rabbit
      RESULT: redis
      LOCK: filesystem
    - TOX_ENV: py36
      BROKER: rabbit
      RESULT: redis
      LOCK: filesystem
    - TOX_ENV: py
      PYTHON: Python37-x64
      BROKER: rabbit
      RESULT: redis
      LOCK: filesystem
    - TOX_ENV: py
      PYTHON: Python36-x64
      BROKER: rabbit
      RESULT: redis
      LOCK: filesystem

    - TOX_ENV: lint
      BROKER: sqlite
      RESULT: sqlite
      LOCK: sqlite
    - TOX_ENV: py37
      BROKER: sqlite
      RESULT: sqlite
      LOCK: sqlite
    - TOX_ENV: py36
      BROKER: sqlite
      RESULT: sqlite
      LOCK: sqlite
    - TOX_ENV: py
      PYTHON: Python37-x64
      BROKER: sqlite
      RESULT: sqlite
      LOCK: sqlite
    - TOX_ENV: py
      PYTHON: Python36-x64
      BROKER: sqlite
      RESULT: sqlite
      LOCK: sqlite

    - TOX_ENV: lint
      BROKER: mysql
      RESULT: mysql
      LOCK: mysql
    - TOX_ENV: py37
      BROKER: mysql
      RESULT: mysql
      LOCK: mysql
    - TOX_ENV: py36
      BROKER: mysql
      RESULT: mysql
      LOCK: mysql
    - TOX_ENV: py
      PYTHON: Python37-x64
      BROKER: mysql
      RESULT: mysql
      LOCK: mysql
    - TOX_ENV: py
      PYTHON: Python36-x64
      BROKER: mysql
      RESULT: mysql
      LOCK: mysql

    - TOX_ENV: lint
      BROKER: postgres
      RESULT: postgres
      LOCK: postgres
    - TOX_ENV: py37
      BROKER: postgres
      RESULT: postgres
      LOCK: postgres
    - TOX_ENV: py36
      BROKER: postgres
      RESULT: postgres
      LOCK: postgres
    - TOX_ENV: py
      PYTHON: Python37-x64
      BROKER: postgres
      RESULT: postgres
      LOCK: postgres
    - TOX_ENV: py
      PYTHON: Python36-x64
      BROKER: postgres
      RESULT: postgres
      LOCK: postgres

    - TOX_ENV: lint
      BROKER: redis
      RESULT: redis
      LOCK: redis
    - TOX_ENV: py37
      BROKER: redis
      RESULT: redis
      LOCK: redis
    - TOX_ENV: py36
      BROKER: redis
      RESULT: redis
      LOCK: redis
    - TOX_ENV: py
      PYTHON: Python37-x64
      BROKER: redis
      RESULT: redis
      LOCK: redis
    - TOX_ENV: py
      PYTHON: Python36-x64
      BROKER: redis
      RESULT: redis
      LOCK: redis

# Run.
build_script: pip install tox
after_build:
  - ps: .\testdata\appveyor\setup.ps1

test_script: tox -e %TOX_ENV%
on_success: IF %TOX_ENV% NEQ lint pip install codecov & codecov
